apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

helmCharts:
- name: promtail
  releaseName: promtail
  repo: https://grafana.github.io/helm-charts
  version: 6.11.2
  namespace: logging
  valuesFile: values.yml
