apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
- deployment.yml
- vault-storage.yml

helmCharts:
- name: vault
  releaseName: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.27.0
  valuesFile: values.yml
