apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: home
spec:
  selector:
    app: homeassistant
  ports:
  - name: http
    port: 8123
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  namespace: home
spec:
  serviceName: homeassistant
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Lisbon
        image: ghcr.io/home-assistant/home-assistant:stable
        imagePullPolicy: Always
        name: homeassistant
        volumeMounts:
        - mountPath: /config
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant
  namespace: home
spec:
  hostnames:
  - home.bgalhardo.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external
    namespace: system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: homeassistant
      port: 8123
