apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

resources:
- namespace.yml
- secret-store.yml

helmCharts:
- name: external-secrets
  releaseName: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.8.3
  namespace: external-secrets
