crds:
  create: true
alloy:
  configMap:
    create: false
    name: alloy
    key: config.alloy
  mounts:
    varlog: false
    dockercontainers: false
controller:
  type: deployment
rbac:
  create: true
serviceAccount:
  create: true
configReloader:
  enabled: true
ingress:
  enabled: false

