apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
spec:
  selector:
    matchLabels:
      app: dashy
  replicas: 1
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image:  lissy93/dashy:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /app/public/conf.yml
          name: config
          subPath: conf.yml
      volumes:
      - name: config
        configMap:
          name: dashy
---
apiVersion: v1
kind: Service
metadata:
  name: dashy
spec:
  selector:
    app: dashy
  ports:
    - name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy
spec:
  ingressClassName: nginx
  rules:
  - host: homelab.home
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: dashy
            port:
              number: 80
