apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: plex-secret
  data:
  - secretKey: plex-secret
    remoteRef:
      key: kv/hal9000-control-1/plex
      property: PLEX_TOKEN
