apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-ingress-controller

resources:
- namespace.yml

helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  version: v3.1.0
  namespace: nginx-ingress-controller
  valuesFile: values.yml
