apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
- namespace.yml
- minio-secret.yml
- recurring-job.yml

helmCharts:
- name: longhorn
  repo: https://charts.longhorn.io
  releaseName: longhorn
  version: 1.4.0
  namespace: longhorn-system
  valuesFile: values.yml
