apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-secret
  dataFrom:
  - extract:
      key: kv/hal9000-control-1/longhorn-minio-configs
