apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 20-infra-wiring
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: 10-infra-base
  path: ./kubernetes/20-infra-wiring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
