[poller]
  quiet = true

[prometheus]
  http_listen = "0.0.0.0:9130"
  report_errors = true

[influxdb]
  disable = true

[loki]
  disable = true

[unifi.defaults]
  url = "https://unifi.bgalhardo.internal"
  api_key = "file:///secrets/unifi_api_key"
  sites = ["all"]
  save_sites = true
  save_dpi = true
  verify_ssl = true
