apiVersion: v1
kind: Service
metadata:
  name: homeassistant-hl
spec:
  selector:
    app: homeassistant
  ports:
    - name: headless
      port: 8123
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8123
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
spec:
  serviceName: homeassistant-hl
  selector:
    matchLabels:
      app: homeassistant
  replicas: 1
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Europe/Lisbon
        volumeMounts:
        - mountPath: /config
          name: data
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi
