apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab-pool
spec:
  blocks:
  - start: 192.168.1.230
    stop: 192.168.1.239
  allowFirstLastIPs: "Yes"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ip-policy
spec:
  loadBalancerIPs: true
