apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
- namespace.yml
- config.yml

helmCharts:
- name: metallb
  repo: https://metallb.github.io/metallb
  releaseName: metallb
  version: v0.13.10
  namespace: metallb-system
  valuesFile: values.yml
