apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: plex-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: plex-exporter
    spec:
      containers:
      - name: plex-exporter
        image: ghcr.io/jsclayton/prometheus-plex-exporter
        imagePullPolicy: Always
        env:
        - name: PLEX_SERVER
          value: http://plex.mediacenter:32400
        - name: PLEX_TOKEN
          valueFrom:
            secretKeyRef:
              name: plex-secret
              key: PLEX_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: plex-exporter
  namespace: monitoring
spec:
  selector:
    app: plex-exporter
  ports:
  - name: http
    port: 9000
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-secret-plex-exporter
  namespace: monitoring
spec:
  type: kv-v2
  mount: kv
  path: hal9000/plex-exporter
  destination:
    name: plex-secret
    create: true
  refreshAfter: 30s
