apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

resources:
- deployment.yml

configMapGenerator:
- name: node-files
  files:
  - settings.js
  - flows.json
  options:
    disableNameSuffixHash: true
