apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- deployment.yml

helmCharts:
- name: loki
  releaseName: loki
  repo: https://grafana.github.io/helm-charts
  version: 6.3.4
  namespace: monitoring
  valuesFile: values.yml
