apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
  data:
  - secretKey: cloudflare-api-token
    remoteRef:
      key: kv/hal9000-control-1/cloudflare_api_token
      property: cloudflare_api_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-auth
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflared-auth
  data:
  - secretKey: f33bf363-2ede-4c41-87ce-5099b18ef49d.json
    remoteRef:
      key: kv/hal9000-control-1/cloudflared-auth
      property: f33bf363-2ede-4c41-87ce-5099b18ef49d.json
