esphome:
  name: esp-02
  friendly_name: esp-ble2ha

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api_key

ota:
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# my applications
substitutions:
  govee_1_location: Living Room
  govee_2_location: Babyroom
  govee_3_location: Bedroom
  sensor_location: Office

esp32_ble_tracker:
  scan_parameters:
    active: false
  on_ble_advertise:
  - mac_address: A4:C1:38:EC:C6:28
    then:
    - lambda: |-
        for (auto data : x.get_manufacturer_datas()) {
          if(data.data.size()==6) {
            const int basenum = (int16_t(data.data[1]) << 16) + (int16_t(data.data[2]) << 8) + int16_t(data.data[3]);
            const float temperature = basenum / 10000.0f;
            const float humidity = (basenum % 1000) / 10.0f;
            const float battery_level = uint16_t(data.data[4]) / 1.0f;
            int16_t rssi=x.get_rssi();
            id(govee_1_humidity).publish_state(humidity);
            id(govee_1_temp).publish_state(temperature);
            id(govee_1_rssi).publish_state(rssi);
            id(govee_1_battery).publish_state(battery_level);
          } 
        }
  - mac_address: A4:C1:38:00:5D:34
    then:
    - lambda: |-
        for (auto data : x.get_manufacturer_datas()) {
          if(data.data.size()==6) {
            const int basenum = (int16_t(data.data[1]) << 16) + (int16_t(data.data[2]) << 8) + int16_t(data.data[3]);
            const float temperature = basenum / 10000.0f;
            const float humidity = (basenum % 1000) / 10.0f;
            const float battery_level = uint16_t(data.data[4]) / 1.0f;
            int16_t rssi=x.get_rssi();
            id(govee_2_humidity).publish_state(humidity);
            id(govee_2_temp).publish_state(temperature);
            id(govee_2_rssi).publish_state(rssi);
            id(govee_2_battery).publish_state(battery_level);
          } 
        }
  - mac_address: A4:C1:38:4C:B8:0C
    then:
    - lambda: |-
        for (auto data : x.get_manufacturer_datas()) {
          if(data.data.size()==6) {
            const int basenum = (int16_t(data.data[1]) << 16) + (int16_t(data.data[2]) << 8) + int16_t(data.data[3]);
            const float temperature = basenum / 10000.0f;
            const float humidity = (basenum % 1000) / 10.0f;
            const float battery_level = uint16_t(data.data[4]) / 1.0f;
            int16_t rssi=x.get_rssi();
            id(govee_3_humidity).publish_state(humidity);
            id(govee_3_temp).publish_state(temperature);
            id(govee_3_rssi).publish_state(rssi);
            id(govee_3_battery).publish_state(battery_level);
          } 
        }
sensor:
  # Govee 1
  - platform: template
    name: $govee_1_location Temperature
    id: govee_1_temp
    unit_of_measurement: °C
    device_class: temperature
    accuracy_decimals: 1
  - platform: template
    name: $govee_1_location Humidity
    id: govee_1_humidity
    unit_of_measurement: "%"
    device_class: humidity
    accuracy_decimals: 0
  - platform: template
    name: $govee_1_location Sensor Battery Level
    id: govee_1_battery
    unit_of_measurement: "%"
    device_class: humidity
    accuracy_decimals: 0
  - platform: template
    name: $govee_1_location Sensor Signal Strength
    id: govee_1_rssi
    unit_of_measurement: dBm
    accuracy_decimals: 0
  # Govee 2
  - platform: template
    name: $govee_2_location Temperature
    id: govee_2_temp
    unit_of_measurement: °C
    device_class: temperature
    accuracy_decimals: 1
  - platform: template
    name: $govee_2_location Humidity
    id: govee_2_humidity
    unit_of_measurement: "%"
    device_class: humidity
    accuracy_decimals: 0
  - platform: template
    name: $govee_2_location Sensor Battery Level
    id: govee_2_battery
    unit_of_measurement: "%"
    accuracy_decimals: 0
  - platform: template
    name: $govee_2_location Sensor Signal Strength
    id: govee_2_rssi
    unit_of_measurement: dBm
    accuracy_decimals: 0
  # Govee 3
  - platform: template
    name: $govee_3_location Temperature
    id: govee_3_temp
    unit_of_measurement: °C
    device_class: temperature
    accuracy_decimals: 1
  - platform: template
    name: $govee_3_location Humidity
    id: govee_3_humidity
    unit_of_measurement: "%"
    accuracy_decimals: 0
  - platform: template
    name: $govee_3_location Sensor Battery Level
    id: govee_3_battery
    unit_of_measurement: "%"
    accuracy_decimals: 0
  - platform: template
    name: $govee_3_location Sensor Signal Strength
    id: govee_3_rssi
    unit_of_measurement: dBm
    accuracy_decimals: 0
  # DHT11 sensor
  - platform: dht
    model: DHT11
    pin: 23
    temperature:
      name: $sensor_location Temperature
    humidity:
      name: $sensor_location Humidity
    update_interval: 60s
