apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: esphome-secrets 
  data:
  - secretKey: secrets.yaml
    remoteRef:
      key: kv/hal9000-control-1/esphome-secrets 
      property: secrets.yaml
