apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-monitoring

resources:
- deployment.yml
- esphome-secrets.yml

configMapGenerator:
- name: esphome-files
  files:
  - esphome-web-f501b0.yaml
  - esphome-web-02409b.yaml
