defaultVaultConnection:
  enabled: true
  address: "http://192.168.1.173:8200"
defaultAuthMethod:
  enabled: true
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
  serviceAccount: default
tests:
  enabled: false
controller:
  manager:
    logging:
      level: info
