apiVersion: v1
kind: Service
metadata:
  name: plex-hl
spec:
  selector:
    app: plex
  ports:
    - port: 32400
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
spec:
  serviceName: plex-hl
  selector:
    matchLabels:
      app: plex
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /config
          name: data
        - mountPath: /series
          name: series
        - mountPath: /movies
          name: movies
        - mountPath: /transcode
          name: transcode
        env:
        - name: PLEX_UID
          value: "1000"
        - name: PLEX_GID
          value: "1000"
        - name: TZ
          value: Europe/Lisbon
        - name: ADVERTISE_IP
          value: https://plex.bgalhardo.com
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 32400
          timeoutSeconds: 1
      volumes:
      - name: movies
        persistentVolumeClaim:
          claimName: movies
      - name: series
        persistentVolumeClaim:
          claimName: series
      - name: transcode
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  selector:
    app: plex
  ports:
    - name: http
      port: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: plex.bgalhardo.com
    external-dns.alpha.kubernetes.io/target: dynamic.bgalhardo.com
spec:
  ingressClassName: nginx-external
  rules:
  - host: plex.bgalhardo.com
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: plex
            port:
              number: 32400
  tls:
  - hosts:
    - plex.bgalhardo.com
    secretName: plex-ingress
