apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
  data:
  - secretKey: cloudflare-api-token
    remoteRef:
      key: kv/hal9000-control-1/external-dns
      property: cloudflare-api-token
