apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

resources:
- deployment.yml

configMapGenerator:
- name: esphome-files
  files:
  - esp-01.yaml
  - esp-02.yaml
  - esp-03.yaml
  options:
    disableNameSuffixHash: true
