apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk
  maxSize: 12GB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path
provisioning:
  diskSelector:
    match: system_disk
  minSize: 10GB
filesystem:
  type: xfs
