apiVersion: v1alpha1
kind: TrustedRootsConfig
name: homelab-ca
certificates: |-
  -----BEGIN CERTIFICATE-----
  MIIDOzCCAiOgAwIBAgIUCqJTjbkHtArlXOhkkOQGYK4dZskwDQYJKoZIhvcNAQEL
  BQAwJTEjMCEGA1UEAxMaUm9vdCBDQSBiZ2FsaGFyZG8uaW50ZXJuYWwwHhcNMjUw
  NzAxMTUwOTQzWhcNMzUwNjI5MTUxMDEzWjAlMSMwIQYDVQQDExpSb290IENBIGJn
  YWxoYXJkby5pbnRlcm5hbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
  ANI9gdgXFMJS/PUQUAH7kMh7jZ39/nCFTIwvKlo/qJUwCHcy1FgxV0BYkBBdWUDK
  i9fjkt84Y7Dd9Ept+uoQrKo1T5uHkHYyzcR7eJCVXgRk1/IdFp48jjMF6DFVXLQJ
  J9plojMIQspLm0K1L6++ZeOng9vD2fqup4h6mAZF0UQ2kfn7KKLSc0rrQt59Moa7
  8ZBax1Ou2CP5eXMXnZHOZJ2ESu+w+QwPE47lE1hi/fWQ9/1FH/Z46ghZziU5OybF
  w44PJsM64sNWVvUMARhElaXopE8axoiWy3IRfWpRwlbPPUMLN4L9fpbT0+W132I/
  U2VBpM/Kxb92k0VnV86mPkECAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgEGMA8GA1Ud
  EwEB/wQFMAMBAf8wHQYDVR0OBBYEFLz/yYl73+QO91f65J81tj358iHqMB8GA1Ud
  IwQYMBaAFLz/yYl73+QO91f65J81tj358iHqMA0GCSqGSIb3DQEBCwUAA4IBAQCf
  LVcUMiFaYtJnKyfJ5YOLOtv32yZgyYnCC1f59XSVWaWuq+QXiWdqZthX+A36kqwT
  rnNvt0TS9BW6YDkLsmGkmsM6nipoXeTbXuDTcH6zp3Xojb15KReFr6aEvAwglUNm
  Bd40O0TPuLlsspP9c486w9PlqrtSIZ9HRPPoaNJLOWKJZ7FjwvMCJJyU8ycC+SVu
  SOxZW5qXgAgtCvQgOAj/jvA7h3tqzbWC6pndLZO13656ymytZwsqsfj4/Xut4H24
  OiSk4OlJJhJHZBwVZiLGvceSwb6+kpcd9eA9/3XswmCe4BBMf1yH6aWad7W4+ySW
  uFENvBRMycarTrH2fjQ8
  -----END CERTIFICATE-----
