apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.15
        imagePullPolicy: IfNotPresent
        command:
        - mosquitto
        args:
        - -c 
        - mosquitto-no-auth.conf
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              mosquitto_sub -C 1 -W 3 -t '$SYS/#'
          initialDelaySeconds: 3
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1883
        runAsGroup: 1883
        fsGroup: 1883
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
  - name: http
    port: 1883
    protocol: TCP
    targetPort: 1883
  type: LoadBalancer
#---
#apiVersion: gateway.networking.k8s.io/v1alpha2
#kind: TCPRoute
#metadata:
#  name: mosquitto
#spec:
#  parentRefs:
#  - name: local
#    namespace: system
#  rules:
#  - backendRefs:
#    - name: mosquitto
#      port: 1883
