apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: home
spec:
  selector:
    matchLabels:
      app: whisper
  replicas: 1
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper
        image: rhasspy/wyoming-whisper
        imagePullPolicy: IfNotPresent
        args:
        - --model 
        - tiny-int8 
        - --language
        - en 
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: home
spec:
  selector:
    app: whisper
  ports:
    - name: http
      port: 10300
