apiVersion: v1
kind: Service
metadata:
  name: valheim-server
spec:
  selector:
    app: valheim-server
  ports:
    - name: server-1
      port: 2456
      protocol: UDP
    - name: server-2
      port: 2457
      protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: valheim-server-hl
spec:
  selector:
    app: valheim-server
  ports:
    - name: server-1
      port: 2456
      protocol: UDP
    - name: server-2
      port: 2457
      protocol: UDP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valheim-server
spec:
  serviceName: valheim-server-hl
  selector:
    matchLabels:
      app: valheim-server
  replicas: 1
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      containers:
      - name: valheim-server
        image:  lloesche/valheim-server
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: valheim-original
        env:
        - name: TZ
          value: Europe/Lisbon
        - name: BACKUPS_DIRECTORY
          value: /backups
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /backups
          name: backups
      volumes:
      - name: backups
        nfs:
          server: 192.168.1.199
          path: /mnt/Phoenix/valheim-backups/original
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi
