apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valheim-original
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: valheim-original
  dataFrom:
  - extract:
      key: kv/hal9000-control-1/valheim-original
  - extract:
      key: kv/hal9000-control-1/valheim-minio
