apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- deployment.yml

helmCharts:
- name: mimir-distributed
  releaseName: mimir
  repo: https://grafana.github.io/helm-charts
  version: 5.3.0
  namespace: monitoring
  valuesFile: values.yml
