apiVersion: v1
kind: Namespace
metadata:
  name: mediacenter
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.171
    path: /mnt/Movies/Movies
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - talos-worker-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: series
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.171
    path: /mnt/Series/Series
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - talos-worker-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.171
    path: /mnt/Temp/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - talos-worker-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: mediacenter
spec:
  volumeName: movies
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: series
  namespace: mediacenter
spec:
  volumeName: series
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: mediacenter
spec:
  volumeName: downloads
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

