apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: phoenix
scheduler:
  name: ""
spec:
  configuration:
    name: phoenix-env-configuration
  exposeServices: {}
  features:
    domains:
      console: https://phoenix.bgalhardo.com/ui/
  image: minio/minio:RELEASE.2023-05-27T05-56-19Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  mountPath: /export
  env:
  - name: MINIO_PROMETHEUS_URL
    value: http://prometheus-server.prometheus-system
  - name: MINIO_PROMETHEUS_JOB_ID
    value: minio-phoenix
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - phoenix
          topologyKey: kubernetes.io/hostname
    name: ss-0
    resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 931Gi
        storageClassName: directpv-min-io
      status: {}
    volumesPerServer: 1
  requestAutoCert: false
  serviceAccountName: phoenix-sa
  users:
  - name: phoenix-user-1
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
  usage: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phoenix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: phoenix.bgalhardo.com
    external-dns.alpha.kubernetes.io/target: dynamic.bgalhardo.com
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx-external
  rules:
  - host: phoenix.bgalhardo.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /(.*)
        backend:
          service:
            name: phoenix-hl
            port:
              number: 9000
      - pathType: ImplementationSpecific
        path: /ui/(.*)
        backend:
          service:
            name: phoenix-console
            port:
              number: 9090

  tls:
  - hosts:
    - phoenix.bgalhardo.com
    secretName: phoenix-ingress
