apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: phoenix-env-configuration
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: phoenix-env-configuration
  data:
  - secretKey: config.env
    remoteRef:
      key: kv/hal9000-control-1/phoenix-env-configuration
      property: config.env
      decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: phoenix-user-1
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: phoenix-user-1
  dataFrom:
  - extract:
      key: kv/hal9000-control-1/phoenix-user-1
