apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: phoenix
scheduler:
  name: ""
spec:
  configuration:
    name: phoenix-env-configuration
  exposeServices: {}
  image: minio/minio:RELEASE.2023-05-27T05-56-19Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - phoenix
          topologyKey: kubernetes.io/hostname
    name: ss-0
    resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 931Gi
        storageClassName: directpv-min-io
      status: {}
    volumesPerServer: 1
  requestAutoCert: false
  serviceAccountName: phoenix-sa
  users:
  - name: phoenix-user-1
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
  usage: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phoenix
spec:
  ingressClassName: nginx
  rules:
  - host: phoenix.home
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: phoenix-console
            port:
              number: 9090
  tls:
  - hosts:
    - phoenix.home
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phoenix-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 0
spec:
  ingressClassName: nginx
  rules:
  - host: phoenix-api.home
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: phoenix-hl
            port:
              number: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: phoenix-api-external
spec:
  selector:
    v1.min.io/tenant: phoenix
  ports:
    - name: http-external
      port: 9000
  type: LoadBalancer
