apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alloy
  namespace: monitoring
spec:
  hostnames:
  - alloy.bgalhardo.local
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: local
    namespace: system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: alloy
      port: 12345
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alloy-loki-proxy
  namespace: monitoring
spec:
  hostnames:
  - logs.bgalhardo.local
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: local
    namespace: system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: alloy-loki-proxy
      port: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: alloy-loki-proxy
  namespace: monitoring
spec:
  selector:
    app: alloy
  ports:
  - name: http
    port: 9999
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-secret-homeassistant-token
  namespace: monitoring
spec:
  type: kv-v2
  mount: kv
  path: hal9000/alloy-homeassistant-token
  destination:
    name: alloy-homeassistant-token
    create: true
  refreshAfter: 30s
