apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- deployment.yml

configMapGenerator:
- name: alloy
  files:
  - config.alloy
  options:
    disableNameSuffixHash: true

helmCharts:
- name: alloy
  releaseName: alloy
  repo: https://grafana.github.io/helm-charts
  version: 0.1.1
  namespace: monitoring
  valuesFile: values.yml
