apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-monitoring

resources:
- deployment.yml
- node-red-ha-auth.yml

configMapGenerator:
- name: node-files
  files:
  - settings.js
  - flows.json
