apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: node-red-ha-token
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: node-red-ha-token
  data:
  - secretKey: flows_cred.json
    remoteRef:
      key: kv/hal9000-control-1/node-red-ha-token
      property: flows_cred.json
