apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
- namespace.yml
- external-secret.yml
- issuer-lets-encrypt.yml 

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  version: v1.13.1
  namespace: cert-manager
  valuesFile: values.yml
