{
 "title": "Homelab Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Monitored Loads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "ha_sensor_power_w", "legendFormat": "{{friendly_name}}" }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 6, "x": 9, "y": 0 } },
  {
   "title": "Download/Upload speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ha_sensor_data_rate_mbit_per_s{entity=\"sensor.speedtest_download\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ha_sensor_data_rate_mbit_per_s{entity=\"sensor.speedtest_upload\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_uptime_seconds{instance=\"192.168.1.198\", id=\"node/prometheus\"}",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"192.168.1.198\", id=~\"qemu.+\"} * pve_cpu_usage_limit{instance=\"192.168.1.198\", id=~\"qemu.+\"} / on() group_left pve_cpu_usage_limit{instance=\"192.168.1.198\", id=\"node/prometheus\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_size_bytes{instance=\"192.168.1.198\", id=\"node/prometheus\"}",
     "legendFormat": "Host Total"
    },
    {
     "expr": "pve_memory_usage_bytes{instance=\"192.168.1.198\", id=\"node/prometheus\"}",
     "legendFormat": "Host Used"
    },
    {
     "expr": "pve_memory_usage_bytes{instance=\"192.168.1.198\", id=~\"qemu.+\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}