apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-secrets-operator

resources:
- namespace.yml

helmCharts:
- name: vault-secrets-operator
  releaseName: vault-secrets-operator
  repo: https://helm.releases.hashicorp.com
  version: 0.5.1
  valuesFile: values.yml  
  includeCRDs: true
