apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  selector:
    matchLabels:
      app: unbound
  replicas: 1
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: mvance/unbound:latest
        volumeMounts:
        - mountPath: /opt/unbound/etc/unbound/a-records.conf
          name: records
          subPath: a-records.conf
      volumes:
      - name: records
        configMap:
          name: unbound
---
apiVersion: v1
kind: Service
metadata:
  name: unbound
spec:
  selector:
    app: unbound
  ports:
    - name: unbound-tcp
      port: 53
      protocol: TCP
    - name: unbound-udp
      port: 53
      protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound
data:
  a-records.conf: |
    local-zone: "home" redirect
    local-data: "home 86400 IN A 192.168.1.240"
