apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-system

resources:
- namespace.yml

helmCharts:
- name: prometheus
  namespace: prometheus-system
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus
  version: 22.5.0
  valuesFile: values.yml
