apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prometheus
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.199
    path: /mnt/Phoenix/prometheus
