apiVersion: v1
kind: Service
metadata:
  name: overseerr-hl
spec:
  selector:
    app: overseerr
  ports:
    - name: http
      port: 5055
  clusterIP: None  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: overseerr
spec:
  serviceName: overseer-hl
  selector:
    matchLabels:
      app: overseerr
  replicas: 1
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
      - name: overseerr
        image: lscr.io/linuxserver/overseerr:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /config
          name: data
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Europe/Lisbon
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 200Mi
