apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-movies
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.199
    path: /mnt/Phoenix/Movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-series
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.199
    path: /mnt/Phoenix/Series
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.199
    path: /mnt/Phoenix/downloads
