apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-movies
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /disks/Leviathan/Movies
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-series
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /disks/Bahamut/Series
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-downloads
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /disks/Titan/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-1
