apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
spec:
  volumeName: local-movies
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: series
spec:
  volumeName: local-series
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  volumeName: local-downloads
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

