{
 "title": "Homelab Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Monitored Loads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "ha_sensor_power_w", "legendFormat": "{{friendly_name}}" }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 6, "x": 9, "y": 0 } },
  {
   "title": "Download/Upload speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ha_sensor_unit_mbit_per_s{entity=\"sensor.speedtest_download\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ha_sensor_unit_mbit_per_s{entity=\"sensor.speedtest_upload\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Homelab UPS",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ha_sensor_unit_percent{entity=\"sensor.office_ups_load\"}",
     "legendFormat": "load"
    },
    {
     "expr": "ha_sensor_battery_percent{entity=\"sensor.office_ups_battery_charge\"}",
     "legendFormat": "battery"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"hermes\"}-node_boot_time_seconds{instance=\"hermes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_uptime_seconds{instance=\"192.168.1.198\", id=\"node/prometheus\"}",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "truenas_uptime_uptime", "legendFormat": "atlas" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"hermes\",}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"hermes\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=\"hermes\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"hermes\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=\"hermes\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"hermes\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"192.168.1.198\", id=\"node/prometheus\"}",
     "legendFormat": "Host"
    },
    {
     "expr": "pve_cpu_usage_ratio{instance=\"192.168.1.198\", id=~\"qemu/101|qemu/102|qemu/105|qemu/108\"} * pve_cpu_usage_limit{instance=\"192.168.1.198\", id=~\"qemu/101|qemu/102|qemu/105|qemu/108\"} / on() group_left pve_cpu_usage_limit{instance=\"192.168.1.198\", id=\"node/prometheus\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "truenas_aggregation_cpu_cpu_system{device=\"average\"}",
     "legendFormat": "Busy System"
    },
    {
     "expr": "truenas_aggregation_cpu_cpu_user{device=\"average\"}",
     "legendFormat": "Busy User"
    },
    {
     "expr": "truenas_aggregation_cpu_cpu_idle{device=\"average\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"hermes\"} - node_memory_MemFree_bytes{instance=\"hermes\"} - (node_memory_Cached_bytes{instance=\"hermes\"} + node_memory_Buffers_bytes{instance=\"hermes\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"hermes\"} + node_memory_Buffers_bytes{instance=\"hermes\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"hermes\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"hermes\"} - node_memory_SwapFree_bytes{instance=\"hermes\"}",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_size_bytes{instance=\"192.168.1.198\", id=\"node/prometheus\"}",
     "legendFormat": "Host Total"
    },
    {
     "expr": "pve_memory_usage_bytes{instance=\"192.168.1.198\", id=\"node/prometheus\"}",
     "legendFormat": "Host Used"
    },
    {
     "expr": "pve_memory_usage_bytes{instance=\"192.168.1.198\", id=~\"qemu/101|qemu/102|qemu/105|qemu/108\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "truenas_memory_used", "legendFormat": "RAM Used" },
    {
     "expr": "truenas_memory_cached + truenas_memory_buffered",
     "legendFormat": "RAM Cache + Buffer"
    },
    { "expr": "truenas_memory_free", "legendFormat": "RAM Free" },
    { "expr": "truenas_swap_swap_used", "legendFormat": "SWAP Used" }
   ]
  }
 ]
}