apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- deployment.yml

configMapGenerator:
- name: grafana-custom-dashboards
  files:
  - dashboards/homelab-dashboard.json
  - dashboards/loki-dashboard.json
  - dashboards/kubernetes-dashboard.json
  options:
    disableNameSuffixHash: true
generatorOptions:
  labels:
    grafana_dashboard: "1"

helmCharts:
- name: grafana
  namespace: monitoring
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana
  valuesFile: values.yml
  version: 7.3.9
