apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

configMapGenerator:
- name: homelab-dashboard
  files:
  - homelab-dashboard.json
  - loki-dashboard.json
generatorOptions:
  labels:
    grafana_dashboard: "1"

helmCharts:
- name: grafana
  namespace: monitoring
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana
  valuesFile: values.yml
