apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.15
        imagePullPolicy: IfNotPresent
        command:
        - mosquitto
        args:
        - -c 
        - mosquitto-no-auth.conf
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - name: http
      port: 1883
      protocol: TCP
      targetPort: 1883
  type: LoadBalancer
