apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pve-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pve-secret
  data:
  - secretKey: pve-secret
    remoteRef:
      key: kv/hal9000-control-1/prometheus-pve-exporter
      property: PVE_TOKEN_VALUE
