services:
  omni:
    container_name: omni
    image: ghcr.io/siderolabs/omni:v1.11.0
    devices:
      - /dev/net/tun
    volumes:
      - ./etcd:/_out/etcd
      - ./sqlite:/_out/sqlite
      - ./omni.asc:/omni.asc
      - ./certs/server-chain.pem:/server-chain.pem
      - ./certs/server-key.pem:/server-key.pem
      - ./certs/combined-ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    command: >
      --name=omni
      --cert=/server-chain.pem
      --key=/server-key.pem
      --machine-api-cert=/server-chain.pem
      --machine-api-key=/server-key.pem
      --private-key-source='file:///omni.asc'
      --event-sink-port=8091
      --bind-addr=0.0.0.0:443
      --machine-api-bind-addr=0.0.0.0:8090
      --k8s-proxy-bind-addr=0.0.0.0:8100
      --advertised-api-url=https://omni.bgalhardo.internal
      --advertised-kubernetes-proxy-url=https://omni.bgalhardo.internal:8100
      --siderolink-api-advertised-url=https://omni.bgalhardo.internal:8090
      --siderolink-wireguard-advertised-addr=192.168.1.171:5018
      --sqlite-storage-path=/_out/sqlite/omni.db
      --initial-users=bgalhardo@gmail.com
      --eula-accept-name="Bruno Galhardo"
      --eula-accept-email=bgalhardo@gmail.com
      --auth-auth0-enabled=false
      --auth-oidc-enabled=true
      --auth-oidc-provider-url=https://authentik.bgalhardo.internal/application/o/omni/
      --auth-oidc-client-id=
      --auth-oidc-client-secret=
      --auth-oidc-scopes=openid --auth-oidc-scopes=profile --auth-oidc-scopes=email
    restart: always
