apiVersion: v1
kind: Namespace
metadata:
  name: nginx-gateway
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nginx-gateway-fabric
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    nginxGateway:
      gatewayClassName: nginx
