apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

resources:
  - namespace.yml
  - ollama.yml
  - ollama-gpu.yml
  - litellm.yml
  - openwebui.yml

patches:
  - target: { kind: Deployment, name: ollama }
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector
        value: { homelab/node: hades }
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - { key: node.kubernetes.io/unreachable, operator: Exists, effect: NoExecute }
          - { key: node.kubernetes.io/not-ready,  operator: Exists, effect: NoExecute }
  - target: { kind: Deployment, name: litellm|openwebui }
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector
        value: { homelab/node: apollo }
  - target: { kind: Deployment, name: ollama-gpu }
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector
        value: { homelab/gpu: nvidia }
