apiVersion: v1
kind: Service
metadata:
  name: valheim-server
  namespace: gaming
spec:
  selector:
    app: valheim-server
  ports:
    - name: server-1
      port: 2456
      protocol: UDP
    - name: server-2
      port: 2457
      protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: valheim-server-hl
  namespace: gaming
spec:
  selector:
    app: valheim-server
  ports:
    - name: server-1
      port: 2456
      protocol: UDP
    - name: server-2
      port: 2457
      protocol: UDP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valheim-server
  namespace: gaming
spec:
  serviceName: valheim-server-hl
  selector:
    matchLabels:
      app: valheim-server
  replicas: 1
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      containers:
      - name: valheim-server
        image:  lloesche/valheim-server
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: valheim-original
        env:
        - name: SERVER_PORT
          value: "2456"
        - name: TZ
          value: Europe/Lisbon
        - name: BACKUPS
          value: "true"
        - name: BACKUPS_CRON
          value: "0 * * * *"
        - name: BACKUPS_MAX_AGE
          value: "3"
        - name: BACKUPS_MAX_COUNT
          value: "0"
        - name: BACKUPS_IF_IDLE
          value: "false"
        - name: BACKUPS_IDLE_GRACE_PERIOD
          value: "3600"
        - name: BACKUPS_DIRECTORY
          value: /backups
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /backups
          name: backups
      - name: valheim-backup
        # todo: create custom cron image with mc
        image: minio/mc
        command: 
        - /bin/bash 
        - -c
        - |
          mc alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
          while true; do
            mc mirror /backups minio/valheim/original
            sleep 3600; 
          done
        envFrom:
        - secretRef:
            name: valheim-minio
        volumeMounts:
        - mountPath: /backups
          name: backups
      volumes:
      - name: backups
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-secret-valheim-original
  namespace: gaming
spec:
  type: kv-v2
  mount: kv
  path: hal9000/valheim-original
  destination:
    name: valheim-original
    create: true
  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-secret-valheim-minio
  namespace: gaming
spec:
  type: kv-v2
  mount: kv
  path: hal9000/valheim-minio
  destination:
    name: valheim-minio
    create: true
  refreshAfter: 30s

