apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: vault
  namespace: system
  labels:
    kubernetes.io/service-name: vault
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.1.173
ports:
  - name: http
    port: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: system
spec:
  ports:
    - name: http
      port: 8200
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault
  namespace: system
spec:
  hostnames:
  - vault.bgalhardo.local
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: local
    namespace: system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: vault
      port: 8200
    matches:
    - path:
        type: PathPrefix
        value: /
